name: CI Pipeline

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define jobs
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.MY_ACCESS }}
          aws-secret-access-key: ${{ secrets.MY_SECRET }}
          aws-region: ${{ secrets.MY_REGION || 'us-east-1' }}

      # Deploy API Gateway using AWS CLI
      - name: Deploy API Gateway
        run: | 
           curl -X GET https://5ecyb3j068.execute-api.us-east-1.amazonaws.com/my_stage1

  test:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js (example for a Node.js project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install
        
      - id: jq
        uses: direct-actions/jq@v1
        with:
            input-command: uuidgen
            filter: |
             def now_plus_minutes($minutes):
             now | round + (60 * $minutes)
             ;
              {
               exp: now_plus_minutes(60 * 24 * 7),  # now + 1 week
               iat: now_plus_minutes(0),            # now
               jti: .,                              # use UUID generated by input-command
               nbf: now_plus_minutes(60),           # now + 1 hour
             }
             raw-input: true

      - name: JSON Web Token (JWT) - Encode custom token
        uses: ./
        with:
            payload: ${{ steps.jq.outputs.output }}
            secret: RaNDoM+S3cR3t  

      # Run tests
      - name: Run tests
        run: npm test
